source "https://github.com/CocoaPods/Specs.git"
use_frameworks!

target "KZSideDrawerController_Example", :exclusive => true do
  pod "KZSideDrawerController", :path => "../"

  pod "PureLayout"
end

target "KZSideDrawerController_Tests", :exclusive => true do
  pod "KZSideDrawerController", :path => "../"
end
