language: objective-c
matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode7.2
    - osx_image: xcode7.1
    - osx_image: xcode7
before_install:
  - pod install --project-directory=Example
script:
  - set -o pipefail
  - xcodebuild -workspace Example/KZSideDrawerController.xcworkspace -scheme KZSideDrawerController-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s Plus' ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint --allow-warnings
